# -*- coding: utf-8 -*-
"""Aula1 _Pandas_Dio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dySaFcdWo2dWClt_87EJ-IU4YHxXpbU7
"""

print('olá mundo')

#importando a biblioteca pandas
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/curso pandas dio/datasets/Gapminder.csv',error_bad_lines=False, sep=";")

#visualizando as 5 primeiras linhas
df.head()

df = df.rename(columns= {"country":"Pais","continent":"continente","year":"ano","lifeExp":"expectativa de vida","pop":"popToltal","gdpPercap":"Pib"})

df



df.columns

df.dtypes

df.tail(10)

df.describe

df.describe()

df['continente'].unique()

df['Pais'].unique()

Brasil = df.loc[df["Pais"]== "Brazil"]

Brasil

americas = df.loc[df["continente"]== "Americas"]

americas

americas.head(30)

df.groupby("continente")["Pais"].nunique()

Brasil.groupby("ano")["expectativa de vida"].mean()

