# -*- coding: utf-8 -*-
"""Aula Analise exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11gMzI0MTA8_VWJvffyJoUpEx0YvsPau_
"""

#Importando
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('tableau-colorblind10')

#upload
from google.colab import files
file = files.upload()

df = pd.read_excel('AdventureWorks.xlsx')

df

#quantidade d elinhas e colunas
df.shape

#verificando tipos de dados
df.dtypes

#Receita total

df['Valor Venda'].sum()

#custo total
df['custo total'] = df['Custo Unitário'] * df['Quantidade']

df

round(df['custo total'].sum(),2)

df['Lucro'] = df['Valor Venda'] - df['custo total'] #criando coluna de lucro

df

#Lucro total

round(df['Lucro'].sum(),2)

#Criando uma coluna com total de dias ára enviar produto
df['Tempo envio'] = (df['Data Envio'] - df['Data Venda']).dt.days

df

df.dtypes

df.groupby('Marca')['Tempo envio'].mean() #media de tempo de envio por marca



df.groupby('Produto')['Tempo envio'].mean() #Media de tempo de envio por produto

#Verificando se há valores ausentes
df.isnull().sum()

#Vamos agrupar por ano e por marca
df.groupby([df['Data Venda'].dt.year, 'Marca'])['Lucro'].sum()

pd.options.display.float_format = '{:1,.2f}'.format

#reset index - visualizando com colunas
lucro_ano =df.groupby([df['Data Venda'].dt.year, 'Marca'])['Lucro'].sum().reset_index()

lucro_ano

#Qual o total de produtos vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

#grafico Total de produtos vendidos

df.groupby('Produto')["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total de produtos vendidos");

#Lucro por ano

df.groupby(df['Data Venda'].dt.year)['Lucro'].sum().plot.bar(title="Lucro X Ano");



#Lucro por ano

df.groupby(df['Data Venda'].dt.year)['Lucro'].sum()

#Filtrando vendas dee 2009
df_2009 = df[df['Data Venda'].dt.year == 2009]

df_2009

df_2009.groupby(df_2009['Data Venda'].dt.month)['Lucro'].sum().plot(title = 'Lucro x Mês');

#Lucro por marcar grafico



df_2009.groupby('Marca')['Lucro'].sum().plot.bar(title='Lucro x Marca');
plt.xlabel('Marca')
plt.ylabel('Lucro')
plt.xticks(rotation='horizontal');

df_2009

df['Tempo envio'].describe()

#Grafico de Boxplot
plt.boxplot(df['Tempo envio']);

#misistogram
plt.hist(df['Tempo envio']);

#tempo minimo de envio
plt.hist(df['Tempo envio']);

#Tempo minimo de envio
df['Tempo envio'].min()

#Tempo maxo de envio
df['Tempo envio'].max()

#Identificando a ouliner 
df[df['Tempo envio']== 20]

df.to_csv('df_vendas_novo.csv', index=False)